DELETE FROM regions;
DELETE FROM region_types;
DELETE FROM compilation_events;
DELETE FROM compilations;
DELETE FROM requests;
DELETE FROM events;
DELETE FROM users;
DELETE FROM categories;
DELETE FROM locations;

ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE categories ALTER COLUMN id RESTART WITH 1;
ALTER TABLE locations ALTER COLUMN id RESTART WITH 1;
ALTER TABLE events ALTER COLUMN id RESTART WITH 1;
ALTER TABLE requests ALTER COLUMN id RESTART WITH 1;
ALTER TABLE compilations ALTER COLUMN id RESTART WITH 1;
ALTER TABLE region_types ALTER COLUMN id RESTART WITH 1;
ALTER TABLE regions ALTER COLUMN id RESTART WITH 1;